#include "input_update.hpp"
#include "position_update.hpp"
#include "reset_collision_flags.hpp"
#include "collision_update.hpp"
#include "update_hitbox_position.hpp"
#include "update_remove_after_lifetime.hpp"
#include "update.hpp"
#include "render.hpp"
